### ISSUE TITLE
Exceeded rate limits: too many api requests per user per method for this user_method

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#103]
https://console.cloud.google.com/errors/detail/CNOogs2U-fCpFg;time=PT1H;refresh=true?project=httparchive

> "errors": [ { "message": "Exceeded rate limits: too many api requests per user per method for this user_method. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas", "domain": "usageLimits", "reason": "rateLimitExceeded" } ], "status": "PERMISSION_DENIED" } } > [while running 'WriteNonSummaryTables/WriteLighthouseHome2/WriteToBigQuery/_StreamToBigQuery/StreamInsertRows/ParDo(BigQueryWriteFn)-ptransform-63']

This might just be a normal crawl startup error, but filing a bug in case it's worth investigating and fixing

**Comment by giancarloaf** [comment]
[Thundering herd](https://en.wikipedia.org/wiki/Thundering_herd_problem) due to multiple non-summary BigQuery table writing steps trying to create the same tables concurrently.

Should be fixed by limiting partitioning non-summary BigQuery table writing steps to 1 (from the default 4). See PR #105

**Comment by giancarloaf** [comment]
Resolved this error group
https://console.cloud.google.com/errors/detail/CPj1xLrQ_vXzKQ;time=P1D?project=httparchive

**Comment by giancarloaf** [comment]
Reopening. The previous change reduced but did not completely resolve the issue.

**Comment by giancarloaf** [comment]
Seems related to #110
