### ISSUE TITLE
Summary statistics for BigQuery `all` tables

### ISSUE THREAD

**Issue by giancarloaf** [HTTPArchive/data-pipeline#124]
When the data pipeline is complete, counts and sizes for the `all` tables should be collected and made available for the Data Studio dashboard.

https://datastudio.google.com/u/0/reporting/1jh_ScPlCIbSYTf2r2Y6EftqmX9SQy4Gn/page/p_an38lbzywc

> * successfully tested and loaded to BigQuery (home and secondary)
Each should also be broken down by desktop and mobile.

_Originally posted by @giancarloaf in https://github.com/HTTPArchive/data-pipeline/issues/3#issuecomment-1196168984_

**Comment by tunetheweb** [comment]
@max-ostapenko implemented this.
