### ISSUE TITLE
Document how the new analysis pipeline works, including metrics

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#21]
Owner: @giancarloaf
Supporters: @rviscomi @tunetheweb @paulcalvano 

As a follow-up to #6, any new functionality added for #19 should be well-documented in the wiki.

We should also document the metrics that are included in the monthly analysis.

**Comment by max-ostapenko** [comment]
Documented in readme (https://github.com/HTTPArchive/dataform/) and [www.har.fyi](https://har.fyi/)
