### ISSUE TITLE
Dataflow job failure: crawl-combined-desktop-20240227-042336-753436z

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#245]
```
Error encountered with the status channel: There are 5 consecutive failures obtaining SDK worker status info. SDK worker appears to be dead. Aborting SDK sdk-0-0_sibling_25
```

[Error log](https://console.cloud.google.com/dataflow/jobs/us-west1/2024-02-28_11_47_00-955434979732929990;bottomTab=JOB_LOGS;logsSeverity=ERROR;graphView=0?project=httparchive&pageState=(%22dfTime%22:(%22l%22:%22dfJobMaxTime%22)))

Not exactly sure what happened or if it's related or just coincidental to #244 #243. Maybe a GCE worker crashed randomly?

**Comment by max-ostapenko** [comment]
Stale issue. Dataflow is not used anymore.
