### ISSUE TITLE
Summary data in `all.requests` issues

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/data-pipeline#257]
Found this out while looking at the combined pipeline issues.

The `all` pipeline has the following issues

- It's `null` for 404s and other errors, even though these have summary data in the legacy `summary_requests` table.
- It doesn't set `firstReq` and `firstHtml` correctly (they are always set to `true`).

This is because we call the summary code per request here:

https://github.com/HTTPArchive/data-pipeline/blob/d0479063a3d7cc59723f4c71947c041276262852/modules/import_all.py#L341-L346

And that code was more intended to be called in one go since it does this:

https://github.com/HTTPArchive/data-pipeline/blob/d0479063a3d7cc59723f4c71947c041276262852/modules/transformation.py#L406-L425

You basically need to generate the whole page and all requests, and then lookup this `summary_requests` array for each request:

```py
    try:
        _, requests = HarJsonToSummary.generate_pages(file_name, har)
    except Exception:
        logging.exception(
            f"Unable to unpack HAR, check previous logs for detailed errors. "
            f"{file_name=}, {har=}"
        )
        return None

    summary_requests = []

    for request in requests:

        try:
            wanted_summary_fields = [
                field["name"]
                for field in constants.BIGQUERY["schemas"]["summary_requests"]["fields"]
            ]

            request = utils.dict_subset(request, wanted_summary_fields)
        except Exception:
            logging.exception(
                f"Unable to unpack HAR, check previous logs for detailed errors. "
                f"{file_name=}, {har=}"
            )
            continue

        if request:
            summary_requests.append(request)
```

**Comment by pmeenan** [comment]
This should be fixed in the streaming writes from the agent for the next crawl: https://github.com/HTTPArchive/wptagent/commit/53189db52e8d4eab783a5ae39ffa5d638c69d0bc

**Comment by tunetheweb** [comment]
This looks good now in the new dataset 🎉
