### ISSUE TITLE
Optimize GCP costs

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#27]
Owner: @giancarloaf 
Supporters: @rviscomi @pmeenan 

We need to do a deeper accounting of our GCP costs and have a better understanding of what the new pipeline will cost at full capacity. With that information, we should also identify practical ways to reduce costs and start implementing some of the low-hanging fruit.

For example, we have 1.3 petabytes in the [nearline class](https://cloud.google.com/storage/docs/storage-classes#nearline) of Cloud Storage. If we switch to the archive class we could [save](https://cloud.google.com/storage/pricing#price-tables) 88% ($10k/month).

**Comment by rviscomi** [comment]
Update: @pmeenan adjusted the storage class on GCS today, would be good to see how that affects costs in the billing dashboard.

**Comment by max-ostapenko** [comment]
No current issues with the infra costs.
Some savings pending upon the planned legacy data cleanup in a few months.

Closing.
