### ISSUE TITLE
Add the ability to monitor each stage of the GCP pipeline

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#3]
Add telemetry to the pipeline to measure how each stage is progressing. We should also be able to monitor the progress in some kind of dashboard UI.

Stretch goal: if things go wrong, we should be proactively alerted

**Comment by pmeenan** [comment]
FYI, I set up a "[Crawl](https://pantheon.corp.google.com/monitoring/dashboards/builder/29857dcb-dbb9-4e82-82c3-64ddec07d2f7?project=httparchive&dashboardBuilderState=%257B%2522editModeEnabled%2522:false%257D&timeDomain=1h)" dashboard in GCP. Right now it only has the pubsub queue length for pending tests but we should be able to use standard GCP monitoring for most things.

**Comment by tunetheweb** [comment]
Only for those with Google SSO accounts 😔

**Comment by rviscomi** [comment]
Edited the link so it points to the public GCP domain.

**Comment by pmeenan** [comment]
Whoops, yeah, sorry - it's part of the HA project so we should all have access. I was just using my internal account at the time.

**Comment by tunetheweb** [comment]
Works now!

**Comment by giancarloaf** [comment]
Revisiting this after removing streaming in #119

* how many urls need to be tested (home-only)
* how many urls have been tested (home and secondary pages)
* successfully tested and loaded to BigQuery (home and secondary)

Each should also be broken down by desktop and mobile.

@giancarloaf to chat with @pmeenan on options to get this info during the crawl

**Comment by giancarloaf** [comment]
Notes after revisiting this

- summary information can be gathered in BigQuery
- the current logging information we have is "good enough" @rviscomi 
- reporting will be kicked off from the `worker` VM

**Comment by giancarloaf** [comment]
Consider "metadata reporting" in a future phase.
