### ISSUE TITLE
Keep feature counters up to date

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#30]
Chrome periodically adds new feature counters, which are detected by WebPageTest and the results for which are written to the `blink_features` dataset on BigQuery. This table powers the Chrome Status dashboard (for example, [ServiceWorkerControlledPage](https://chromestatus.com/metrics/feature/timeline/popularity/990)) and is used by web platform teams to explore feature adoption.

Sometimes, the list of features detected by Chrome gets ahead of the list used by WebPageTest. When this happens, WebPageTest will see that Chrome detected a feature but not know how to map its feature ID to a human-readable name (eg `990` is the ID for `ServiceWorkerControlledPage`). The result is that there is a gap in the dataset where users are unable to find a feature by name, which also affects the dashboard.

A couple of ideas:

1. We could fix it at the source by making sure that WebPageTest is always in sync with the [Chrome code](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/public/mojom/web_feature/web_feature.mojom;l=20). This could be done with something like GitHub Actions in the WebPageTest repo to check for changes to the feature list and automatically create a PR to merge them into WebPageTest.

2. Make the feature ID:name map available in BigQuery, so that if the WebPageTest results are out of date, we could backfill the correct name to a given ID. This could be done using a persistent function similar to [`chrome-ux-report.experimental.GET_COUNTRY`](https://console.cloud.google.com/bigquery?p=chrome-ux-report&d=experimental&r=GET_COUNTRY&page=routine), which is just a JS function mapping country codes to country names, like `"us": "United States of America"`. We can update this function as part of the monthly data pipeline to stay in sync with Chrome. When we generate the `blink_features` table, we can mitigate unknown feature names by coalescing any null feature names to the output of this function. That would help ensure that direct queries on the feature table are up to date and the Chrome Status dashboard uses the latest mapping.

Any other ideas or thoughts?

**Comment by max-ostapenko** [comment]
Updates were implemented in the wptagent directly https://github.com/HTTPArchive/wptagent/commit/905c988ee90b1362c538b9d77998904836338278
