### ISSUE TITLE
Discrepancies between experimental and legacy summary_pages pipelines

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#43]
For each field in the `summary_pages` schema, this is how many entries have mismatched values across the experimental and legacy pipelines:

- [x]	pageid	345,348	(100%): _MySQL-generated_
- [x]	createDate	345,348	(100%): _Legacy-specific timestamp when the page was processed ([source](https://github.com/HTTPArchive/legacy.httparchive.org/blob/de08e0c7c94a7da529826f0a4429a9d28b8fdf5e/bulktest/batch_lib.inc#L399))_
- [ ]	maxageNull	344,711	(99%)
- [ ]	maxage0	344,181	(99%)
- [ ]	maxDomainReqs	338,431	(97%)
- [ ]	maxage1	291,715	(84%)
- [ ]	reqTotal	151,838	(43%)
- [ ]	numHttps	136,345	(39%)
- [ ]	bytesTotal	105,605	(30%)
- [ ]	maxage365	105,360	(30%)
- [ ]	startedDateTime	98,287	(28%)
- [ ]	maxage30	97,247	(28%)
- [ ]	onContentLoaded	92,109	(26%)
- [ ]	reqOther	85,727	(24%)
- [ ]	maxageMore	74,710	(21%)
- [ ]	reqHtml	58,251	(16%)
- [ ]	numDomains	53,599	(15%)
- [ ]	reqJS	50,384	(14%)
- [ ]	bytesJS	48,406	(14%)
- [ ]	numCompressed	39,318	(11%)
- [ ]	numRedirects	31,356	(9%)
- [ ]	reqImg	28,900	(8%)
- [ ]	reqText	27,924	(8%)
- [ ]	bytesHtml	26,523	(7%)
- [ ]	bytesOther	26,250	(7%)
- [ ]	bytesImg	23,641	(6%)
- [ ]	bytesText	19,325	(5%)
- [ ]	reqGif	18,942	(5%)
- [ ]	bytesGif	16,097	(4%)
- [ ]	bytesHtmlDoc	10,572	(3%)
- [ ]	numErrors	8,882	(2%)
- [ ]	reqPng	8,469	(2%)
- [ ]	reqJpg	7,463	(2%)
- [ ]	bytesPng	6,612	(1%)
- [ ]	reqXml	5,414	(1%)
- [ ]	bytesXml	5,218	(1%)
- [ ]	TTFB	5,182	(1%)
- [ ]	bytesJpg	5,162	(1%)
- [ ]	wptid	5,140	(1%)
- [ ]	onLoad	5,140	(1%)
- [ ]	fullyLoaded	5,140	(1%)
- [ ]	visualComplete	5,140	(1%)
- [ ]	SpeedIndex	5,134	(1%)
- [ ]	renderStart	5,116	(1%)
- [ ]	gzipTotal	4,946	(1%)
- [ ]	reqVideo	4,485	(1%)
- [ ]	bytesVideo	4,462	(1%)
- [ ]	bytesCSS	4,206	(1%)
- [ ]	_connections	4,120	(1%)
- [ ]	reqCSS	3,744	(1%)
- [ ]	rank	2,844	(0%)
- [ ]	reqFont	2,496	(0%)
- [ ]	bytesFont	2,248	(0%)
- [ ]	gzipSavings	2,064	(0%)
- [ ]	numDomElements	1,957	(0%)
- [ ]	document_height	1,373	(0%)
- [ ]	localstorage_size	1,199	(0%)
- [ ]	bytesSvg	1,076	(0%)
- [ ]	reqSvg	1,073	(0%)
- [ ]	num_scripts	723	(0%)
- [ ]	reqWebp	607	(0%)
- [ ]	num_iframes	598	(0%)
- [ ]	bytesWebp	589	(0%)
- [ ]	bytesAudio	579	(0%)
- [ ]	num_scripts_async	574	(0%)
- [ ]	reqAudio	542	(0%)
- [ ]	sessionstorage_size	364	(0%)
- [ ]	avg_dom_depth	182	(0%)
- [ ]	num_scripts_sync	138	(0%)
- [ ]	document_width	77	(0%)
- [ ]	meta_viewport	30	(0%)
- [ ]	doctype	23	(0%)
- [ ]	cdn	15	(0%)
- [ ]	numGlibs	10	(0%)
- [x]	archive	0	(0%)
- [x]	label	0	(0%)
- [x]	crawlid	0	(0%)
- [x]	wptrun	0	(0%)
- [x]	url	0	(0%)
- [x]	urlShort	0	(0%)
- [x]	urlhash	0	(0%)
- [x]	PageSpeed	0	(0%)
- [x]	reqFlash	0	(0%)
- [x]	reqJson	0	(0%)
- [x]	bytesFlash	0	(0%)
- [x]	bytesJson	0	(0%)
- [x]	_adult_site	0	(0%)
- [x]	usertiming	0	(0%)

There is also a mismatch in some of the URLs themselves. 62,389 URLs (15%) in the experimental table have no matches in the legacy table. Some of those URLs for example:

```
https://megaleiloes.pt/tecnologia/
http://malt300.com/index2.php
https://anno1800.fandom.com/wiki/Anno_1800_Wiki
https://piercingforum.forumcommunity.net/m/
https://www.olivierhyundai.com/fr
https://m.mystake.bet/
https://www.katsurafudosan.jp/sp/
https://shopahavajewels.com/
https://kycde6.infinitecampus.org/blank.jsp
https://savefrom4k.net/en11/
```

These seem to be the redirected URL rather than the original URL.

---

Source query:

```sql
WITH exp AS (
  SELECT
    *
  FROM
    `httparchive.experimental_summary_pages.2022_04_01_mobile`
), prod AS (
  SELECT
    *
  FROM
    `httparchive.summary_pages.2022_04_01_mobile`
)


SELECT
  COUNTIF(exp.pageid != prod.pageid) AS pageid,
  COUNTIF(exp.createDate != prod.createDate) AS createDate,
  COUNTIF(exp.archive != prod.archive) AS archive,
  COUNTIF(exp.label != prod.label) AS label,
  COUNTIF(exp.crawlid != prod.crawlid) AS crawlid,
  COUNTIF(exp.wptid != prod.wptid) AS wptid,
  COUNTIF(exp.wptrun != prod.wptrun) AS wptrun,
  COUNTIF(exp.url != prod.url) AS url,
  COUNTIF(exp.urlShort != prod.urlShort) AS urlShort,
  COUNTIF(exp.urlhash != prod.urlhash) AS urlhash,
  COUNTIF(exp.cdn != prod.cdn) AS cdn,
  COUNTIF(exp.startedDateTime != prod.startedDateTime) AS startedDateTime,
  COUNTIF(exp.TTFB != prod.TTFB) AS TTFB,
  COUNTIF(exp.renderStart != prod.renderStart) AS renderStart,
  COUNTIF(exp.onContentLoaded != prod.onContentLoaded) AS onContentLoaded,
  COUNTIF(exp.onLoad != prod.onLoad) AS onLoad,
  COUNTIF(exp.fullyLoaded != prod.fullyLoaded) AS fullyLoaded,
  COUNTIF(exp.visualComplete != prod.visualComplete) AS visualComplete,
  COUNTIF(exp.PageSpeed != prod.PageSpeed) AS PageSpeed,
  COUNTIF(exp.SpeedIndex != prod.SpeedIndex) AS SpeedIndex,
  COUNTIF(exp.rank != prod.rank) AS rank,
  COUNTIF(exp.reqTotal != prod.reqTotal) AS reqTotal,
  COUNTIF(exp.reqHtml != prod.reqHtml) AS reqHtml,
  COUNTIF(exp.reqJS != prod.reqJS) AS reqJS,
  COUNTIF(exp.reqCSS != prod.reqCSS) AS reqCSS,
  COUNTIF(exp.reqImg != prod.reqImg) AS reqImg,
  COUNTIF(exp.reqGif != prod.reqGif) AS reqGif,
  COUNTIF(exp.reqJpg != prod.reqJpg) AS reqJpg,
  COUNTIF(exp.reqPng != prod.reqPng) AS reqPng,
  COUNTIF(exp.reqFont != prod.reqFont) AS reqFont,
  COUNTIF(exp.reqFlash != prod.reqFlash) AS reqFlash,
  COUNTIF(exp.reqJson != prod.reqJson) AS reqJson,
  COUNTIF(exp.reqOther != prod.reqOther) AS reqOther,
  COUNTIF(exp.bytesTotal != prod.bytesTotal) AS bytesTotal,
  COUNTIF(exp.bytesHtml != prod.bytesHtml) AS bytesHtml,
  COUNTIF(exp.bytesJS != prod.bytesJS) AS bytesJS,
  COUNTIF(exp.bytesCSS != prod.bytesCSS) AS bytesCSS,
  COUNTIF(exp.bytesImg != prod.bytesImg) AS bytesImg,
  COUNTIF(exp.bytesGif != prod.bytesGif) AS bytesGif,
  COUNTIF(exp.bytesJpg != prod.bytesJpg) AS bytesJpg,
  COUNTIF(exp.bytesPng != prod.bytesPng) AS bytesPng,
  COUNTIF(exp.bytesFont != prod.bytesFont) AS bytesFont,
  COUNTIF(exp.bytesFlash != prod.bytesFlash) AS bytesFlash,
  COUNTIF(exp.bytesJson != prod.bytesJson) AS bytesJson,
  COUNTIF(exp.bytesOther != prod.bytesOther) AS bytesOther,
  COUNTIF(exp.bytesHtmlDoc != prod.bytesHtmlDoc) AS bytesHtmlDoc,
  COUNTIF(exp.numDomains != prod.numDomains) AS numDomains,
  COUNTIF(exp.maxDomainReqs != prod.maxDomainReqs) AS maxDomainReqs,
  COUNTIF(exp.numRedirects != prod.numRedirects) AS numRedirects,
  COUNTIF(exp.numErrors != prod.numErrors) AS numErrors,
  COUNTIF(exp.numGlibs != prod.numGlibs) AS numGlibs,
  COUNTIF(exp.numHttps != prod.numHttps) AS numHttps,
  COUNTIF(exp.numCompressed != prod.numCompressed) AS numCompressed,
  COUNTIF(exp.numDomElements != prod.numDomElements) AS numDomElements,
  COUNTIF(exp.maxageNull != prod.maxageNull) AS maxageNull,
  COUNTIF(exp.maxage0 != prod.maxage0) AS maxage0,
  COUNTIF(exp.maxage1 != prod.maxage1) AS maxage1,
  COUNTIF(exp.maxage30 != prod.maxage30) AS maxage30,
  COUNTIF(exp.maxage365 != prod.maxage365) AS maxage365,
  COUNTIF(exp.maxageMore != prod.maxageMore) AS maxageMore,
  COUNTIF(exp.gzipTotal != prod.gzipTotal) AS gzipTotal,
  COUNTIF(exp.gzipSavings != prod.gzipSavings) AS gzipSavings,
  COUNTIF(exp._connections != prod._connections) AS _connections,
  COUNTIF(exp._adult_site != prod._adult_site) AS _adult_site,
  COUNTIF(exp.avg_dom_depth != prod.avg_dom_depth) AS avg_dom_depth,
  COUNTIF(exp.document_height != prod.document_height) AS document_height,
  COUNTIF(exp.document_width != prod.document_width) AS document_width,
  COUNTIF(exp.localstorage_size != prod.localstorage_size) AS localstorage_size,
  COUNTIF(exp.sessionstorage_size != prod.sessionstorage_size) AS sessionstorage_size,
  COUNTIF(exp.num_iframes != prod.num_iframes) AS num_iframes,
  COUNTIF(exp.num_scripts != prod.num_scripts) AS num_scripts,
  COUNTIF(exp.doctype != prod.doctype) AS doctype,
  COUNTIF(exp.meta_viewport != prod.meta_viewport) AS meta_viewport,
  COUNTIF(exp.reqAudio != prod.reqAudio) AS reqAudio,
  COUNTIF(exp.reqVideo != prod.reqVideo) AS reqVideo,
  COUNTIF(exp.reqText != prod.reqText) AS reqText,
  COUNTIF(exp.reqXml != prod.reqXml) AS reqXml,
  COUNTIF(exp.reqWebp != prod.reqWebp) AS reqWebp,
  COUNTIF(exp.reqSvg != prod.reqSvg) AS reqSvg,
  COUNTIF(exp.bytesAudio != prod.bytesAudio) AS bytesAudio,
  COUNTIF(exp.bytesVideo != prod.bytesVideo) AS bytesVideo,
  COUNTIF(exp.bytesText != prod.bytesText) AS bytesText,
  COUNTIF(exp.bytesXml != prod.bytesXml) AS bytesXml,
  COUNTIF(exp.bytesWebp != prod.bytesWebp) AS bytesWebp,
  COUNTIF(exp.bytesSvg != prod.bytesSvg) AS bytesSvg,
  COUNTIF(exp.num_scripts_async != prod.num_scripts_async) AS num_scripts_async,
  COUNTIF(exp.num_scripts_sync != prod.num_scripts_sync) AS num_scripts_sync,
  COUNTIF(exp.usertiming != prod.usertiming) AS usertiming
FROM
  exp
LEFT JOIN
  prod
USING
  (url)
```

**Comment by rviscomi** [comment]
I've checked off any fields that either have no mismatch or aren't expected to match, like the MySQL-generated `requestid`.

**Comment by rviscomi** [comment]
> These seem to be the redirected URL rather than the original URL.

@pmeenan it seems like the HAR files on GCS are losing some info about the page being tested.

For example: https://webpagetest.httparchive.org/result/220501_MxB_2EVU/1/details/#waterfall_view_step1. The GCS URL is `gs://httparchive/crawls/android-May_1_2022/220501_MxB_2EVU.har.gz`.

The page being tested is https://www.tropicana.net/. However, the first request is for the certificate, not the HTML page: http://certificates.godaddy.com/repository/gdig2.crt.

In the HAR file that we use to generate the `summary_pages` table on BigQuery, it seems like the `_URL` field represents the URL of the first request rather than the test page itself. So this ends up populating the table with bad URLs.

```js
// "http://certificates.godaddy.com/repository/gdig2.crt"
har.log.pages[0]._URL
```

```sql
# http://certificates.godaddy.com/repository/gdig2.crt 
SELECT
  url
FROM
  `httparchive.experimental_summary_pages.2022_05_01_mobile`
WHERE
  wptid = '220501_MxB_2EVU'
```

I don't think this was an issue when the summary tables were generated in the legacy pipeline because it kept track of the URLs in MySQL. It's only becoming an issue now that we're generating the summary data from the HARs directly.

This seems like a bug in the HAR generation, but I'm not sure if that's something on our end or WPT. Either way, is this something we can fix by regenerating the HARs? If not, is there any other field in the existing HARs that would be a reliable source for the page URL?

In the tropicana.net case, the page redirects to https://www.caesars.com/tropicana-ac. The `_document_URL` field reflects the redirected URL, not the original page. AFAICT the only other places that logs the original URL of the page are: `har.log.entries[1]. _full_url` but the index is non-deterministic, and `har._lighthouse. requestedUrl` but LH tests are more prone to failure (at least we have desktop data now).

WDYT? Any other ideas to work around this?

**Comment by pmeenan** [comment]
Hmm, usually it skips over the certificates when identifying the main fetch but that one isn't returning any content type associated with it.  The page-level reported URL shouldn't rely on that for the first step of navigation though so it's likely a small tweak will fix it (going forward) - looking now.

If it will help in the short term, I can probably generate a mapping table of test ID's to the URL that was used. They are generated deterministically based on the crawl files and that would help repair the current HARs (or we can just re-run the crawl after it is fixed, potentially while also enabling secondary pages.

**Comment by rviscomi** [comment]
I like the idea of rerunning the crawl with the fix and secondary pages, that would be really nice to have for next month's crawl used by the Almanac.

Before kicking that off, we'd need to coordinate on what to do with all of the in-flight Pub/Sub messages, the HAR data in GCS, and the BQ tables.

**Comment by giancarloaf** [comment]
Yes please! I am performing some updates to the pipeline currently. I think I can can get by by taking a snapshot of of the PubSub topic or backing it up to GCS for testing later so we can rerun the crawl. Please ping before initiating a new crawl.

**Comment by giancarloaf** [comment]
Revisiting this after resolving #72

**Comment by giancarloaf** [comment]
Will rerun the April summary table generation and compare results between legacy and new pipeline.

**Comment by tunetheweb** [comment]
> The page being tested is https://www.tropicana.net/. However, the first request is for the certificate, not the HTML page: http://certificates.godaddy.com/repository/gdig2.crt.

This looks to still be an issue:

```sql
SELECT
  COUNT(0) AS freq,
  url AS page,
FROM
  `httparchive.summary_requests.2022_08_01_mobile`
WHERE
  firstHtml
GROUP BY
  url
HAVING
  COUNT(0) > 1
ORDER BY
  freq DESC
```

but looks to be a WPT issue @pmeenan as this example from https://ibank.agrobank.uz/ shows https://webpagetest.httparchive.org/result/220801_Mx1JK_BWOVO/1/details/#waterfall_view_step1 :
![image](https://user-images.githubusercontent.com/10931297/185632862-054746b8-2bd2-4227-91ff-185591092535.png)

**Comment by pmeenan** [comment]
The pkix-cert issue is fixed now. That mime type wasn't on the list of known cert mime types. The fix is two-leveled, adding the pkix-cert type to the known list but it also added logic to first look for the "sec-fetch-dest: document" request header and only fall-back to the existing logic if a main-frame document navigation can't be found that way first.

Not a new problem, but maybe adoption of that kind of cert has increased.

FWIW, it looks like [EV cert revocation checking might be going away in 106](https://bugs.chromium.org/p/chromium/issues/detail?id=1268848) which will completely solve it.

**Comment by tunetheweb** [comment]
That'll get the Security bloggers fighting with the CA industry again!

**Comment by giancarloaf** [comment]
Some time has passed since these results were generated. We will generate new April tables in the `experimental` dataset using the dataflow pipeline and compare against April's existing legacy tables generated with the MySQL pipeline.

**Comment by rviscomi** [comment]
@giancarloaf is it possible to write to the experimental dataset using the new workflow?

**Comment by rviscomi** [comment]
Obsolete
