### ISSUE TITLE
Rerun 2022_05_01

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#44]
- [x] Make a copy of the first crawl's data on GCS to not be overwritten @giancarloaf 
- [x] Make a copy of the first crawl's data on BigQuery @giancarloaf 
- [x] Enable crawling 1 level of secondary pages @pmeenan 
- [x] Add the ability to distinguish between primary/secondary pages in the Dataflow pipeline @giancarloaf _waiting on #12_ 
- [x] Add metadata to identify the original test URL to the HAR @pmeenan 
- [x] Update the Dataflow pipeline to parse the page `url`, `pageid`, and `requestid` fields from the metadata above @giancarloaf
- [x] Flush Pub/Sub queue before starting the crawl @giancarloaf 
- [x] Restart the summary pipeline @giancarloaf 
- [x] Start the second crawl using the same URLs as before @pmeenan 

Anything else?

**Comment by pmeenan** [comment]
The metadata has a `tested_url` field which has the page URL independent of anything the agent might do (the fixes to report `URL` correctly are also in place but the metadata is safest).

**Comment by rviscomi** [comment]
Lighthouse is updating to 9.6 today. Is it possible to update the test agents before the crawl reruns?

**Comment by pmeenan** [comment]
They will auto update when they spin up as long as the npm stable package
is updated

**Comment by rviscomi** [comment]
@pmeenan: the crawl should be ready to restart when you see this in the morning (Thursday the 12th).

@giancarloaf and I went through the remaining TODO items at the top of this issue and we should be good to go. I left the "flush Pub/Sub queue" one unchecked because we were still seeing some lingering messages coming through from the GCS backup of the first May crawl. @giancarloaf will be monitoring the Pub/Sub messages tonight to ensure that the queue is completely flushed by morning. (If not, at worst we'll have some summary data from both crawls in BQ, which we can clear out in SQL as needed)

**Comment by pmeenan** [comment]
@rviscomi @giancarloaf, It looks like the android and chrome May 1 crawls/ directories have tests in them (from the rogue process moving things around?).  Do they need to be moved into the backup folder first?

**Comment by giancarloaf** [comment]
> @rviscomi @giancarloaf, It looks like the android and chrome May 1 crawls/ directories have tests in them (from the rogue process moving things around?). Do they need to be moved into the backup folder first?

Yep, this is currently in progress using the worker vm. Rick is seeing very slow transfer rate (~100K files per hour) and has decided it would be best to start a new crawl under a different name, to be renamed later.

I will also be restarting the streaming pipeline to incorporate changes from #49 merged earlier today.

**Comment by rviscomi** [comment]
Closing this out. We're rerunning the crawl with today's date to avoid overwriting any of the previous data.
