### ISSUE TITLE
json imported twice leading to CodeQL alert

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/data-pipeline#47]
@giancarloaf noticed this: https://github.com/HTTPArchive/data-pipeline/security/code-scanning/6

It's because of JSON being imported twice:

https://github.com/HTTPArchive/data-pipeline/blob/b230ef86a7845a73b1d735104e9a6c7ed3965896/modules/transformation.py#L2-L6

Thoughts whether we should fix this, and best way to fix (stick with bottom and import `loads` and `dumps` from `json` and remove top `import json`, or stop importing `JSONDecodeError` and instead change reference to `json.JSONDecodeError`?).

**Comment by giancarloaf** [comment]
No strong preference. Going to remove the `JSONDecodeError` import and change the reference to `json.JSONDecodeError`.
