### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/data-pipeline#5]
We OK to add Dependabot to this repo to flag dependency upgrades?

We use it in most of our other repos. Need a file for it to watch though but if I add the Super-Linter in #4 then can start with that and add other files (e.g. Python requirements.txt or node package.json) as we add that code.

**Comment by rviscomi** [comment]
Unclear what if any third parties we'll use but I'm supportive of dependabot if needed.

**Comment by tunetheweb** [comment]
GitHub actions for super linter at least!
