### ISSUE TITLE
Omit secondary pages from canonical BQ tables

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#51]
Until we complete the BQ dataset migration in #15, BQ users shouldn't have to think about handling secondary pages.

We should continue to store primary page data in the canonical BQ datasets:

- summary_pages
- summary_requests
- pages
- requests
- response_bodies
- lighthouse
- technologies
- blink_features
- core_web_vitals
- latest

The rollout process of secondary pages will be:

- [x] Measure secondary pages in the 2022_05_12 crawl (aliased to 05_01 on BQ) as of #12 and #44 
- [x] Continue writing summary tables to the `experimental` dataset
- [x] Create the new table schemas described in #15 
- [x] #81

**Comment by rviscomi** [comment]
Running queries to generate home page only tables for the 2022_05_01 crawl. Here are some examples:

```sql
CREATE OR REPLACE TABLE
  `httparchive.pages.2022_05_01_desktop`
AS
SELECT
  *
FROM
  `httparchive.pages.2022_05_12_desktop`
WHERE
  JSON_VALUE(payload, '$._metadata.crawl_depth') = '0'
```

```sql
CREATE OR REPLACE TABLE
  `httparchive.requests.2022_05_01_mobile`
AS
SELECT
  *
FROM
  `httparchive.requests.2022_05_12_mobile`
WHERE
  page IN (
    SELECT
      url
    FROM
      `httparchive.pages.2022_05_01_mobile`)
```

**Comment by giancarloaf** [comment]
#51 is blocking #12
