### ISSUE TITLE
2022_05_12 response bodies missing

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#59]
The `response_bodies` tables for 2022_05_12 are missing. I think it's because the inclusion of secondary pages increased the write operation beyond the 15 TB limit. We worked around this in the past by bisecting the table and writing it in two stages. Now I think we need 4 stages in order to stay under the limit.

**Comment by rviscomi** [comment]
Update: I let the non-summary Dataflow pipeline run on the desktop crawl for two days before stopping it due to inactivity. I'll need to rerun it with the improvements in https://github.com/HTTPArchive/data-pipeline/pull/64 to avoid blocking execution.

**Comment by rviscomi** [comment]
It seems like capturing response bodies may have been disabled in the May 12 crawl. HARs are not including the `response.content.text` field that usually contains the response bodies for each item in the `entries` array.

Here's a HAR for reference: https://webpagetest.httparchive.org/export.php?bodies=1&pretty=1&test=220512_Dx0_11Ll0

Compared to a HAR from April 2022: https://webpagetest.httparchive.org/export.php?bodies=1&pretty=1&test=220401_Mx10_1YG0

**Comment by pmeenan** [comment]
Argh.  Looks like the templates with the test options were missing the bodies flag.  Just added it but that won't help until the 6/1 crawl.

**Comment by rviscomi** [comment]
Run it again? 😬

**Comment by pmeenan** [comment]
Not sure it is worth an extra run with Jun 1 being just 1 week away anyway.  We can certainly do it but, practically, the results will be about the same and only a week apart.  We should have enough time to complete a cycle by then if you really want to.

**Comment by rviscomi** [comment]
I'm on the fence. Let's chat more and decide tomorrow.
