### ISSUE TITLE
Secondary URLs may not be web pages

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#63]
I noticed one URL of a secondary page on BigQuery is `https://cronic.com.br/wp-content/uploads/2022/01/Balneario-distopica-banner-2.webp`. See the [WPT results](https://webpagetest.httparchive.org/result/220513_Dx16F_93H7V/). This may happen if a home page wraps its LCP image in a link to the image itself.

Ideally, we will go down the list of candidate secondary page URLs until we get one that successfully loads a web page.

Some ideas for ways we can mitigate this:

- Avoid this specific case in the custom metric by ignoring links whose URL matches a nested `<img>` element
- Heuristically avoid images in the custom metric by ignoring URLs that end in (or contain) known image file extensions
- Issue a HEAD request on the server/agent to the URL before submitting the test, ignore URLs whose MIME type is not HTML-like
- Test the page and check the test results on the server/agent
  - `is_base_page` is true but has `image_details`
  - the Lighthouse report fails with a `runtimeError.code` value of `NOT_HTML`

**Comment by pmeenan** [comment]
In that case, the image link isn't the source for any images on the page, it is linked as part of the theme.  Short-term, skipping URLs with some well-known file endings will help (and has been [added](https://github.com/HTTPArchive/crawl/commit/8bd9cb5e49e7529a745a24e41d45a0ed62f9712a#diff-bb74fef1030a52ef7536962baa69697cb072151f81362699592036c78a04c339R227))

It might also be worth adding a custom metric that we use to "validate" that pages were successfully loaded and have it fail for any page that isn't a HTML document and add logic to try deeper links in the crawl for those specific failed cases.  That's a fair bit of plumbing to add though so I'd want to make sure it was necessary before attempting.

**Comment by rviscomi** [comment]
Any advantage to filtering in the agent as opposed to the [custom metric](https://github.com/HTTPArchive/custom-metrics/blob/main/dist/crawl_links.js)?

**Comment by rviscomi** [comment]
SGTM. Closing for now. Let's reevaluate after the next crawl.
