### ISSUE TITLE
Multiple secondary pages for the same root page in May 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#65]
```sql
SELECT
  page,
  rank,
  wptid,
  is_root_page,
  JSON_VALUE(metadata, '$.page_id') AS pageid,
  JSON_VALUE(metadata, '$.root_page_id') AS rootpageid
FROM
  `httparchive.all.pages`
WHERE
  date = '2022-05-01' AND
  client = 'desktop' AND
  JSON_VALUE(metadata, '$.root_page_url') = 'https://www.healthline.com/'
ORDER BY
  pageid
```

page | rank | wptid | is_root_page | pageid | rootpageid
-- | -- | -- | -- | -- | --
`https://www.healthline.com/health-news/what-could-happen-in-the-u-s-if-roe-v-wade-is-overturned` | 1000 | 220512_Dx12Q_8AVDT | FALSE | 13944161 | 4081
`https://www.healthline.com/health/mental-health/reading-quiz?&utm_source=hl&utm_medium=homepage&utm_campaign=mentalwellbeing` | 1000 | 220513_Dx144_8LMAG | FALSE | 14445592 | 4081
`https://www.healthline.com/health/mental-health/reading-quiz?&utm_source=hl&utm_medium=homepage&utm_campaign=mentalwellbeing` | 1000 | 220513_Dx144_8LMAG | FALSE | 14445592 | 4081
`https://www.healthline.com/health/mental-health/reading-quiz?&utm_source=hl&utm_medium=homepage&utm_campaign=mentalwellbeing` | 1000 | 220513_Dx187_9H797 | FALSE | 15919099 | 4081
`https://www.healthline.com/health/mental-health/reading-quiz?&utm_source=hl&utm_medium=homepage&utm_campaign=mentalwellbeing` | 1000 | 220513_Dx187_9H797 | FALSE | 15919099 | 4081
`https://www.healthline.com/` | 1000 | 220512_Dx0_35D | TRUE | 4081 | 4081

There are a couple of unexpected results:

- There are two distinct tests (unique `wptid` and `pageid`) for the same page
- Each test appears twice

Worth investigating if there's an issue with redundant HAR uploads to GCS and/or queueing secondary page tests.

**Comment by rviscomi** [comment]
At one point we discussed crawling more secondary pages for higher ranked origins, so the rank=1000 may somehow be related.

**Comment by rviscomi** [comment]
Ok great. So IIUC this addresses the part about the same page having multiple test IDs, but not the part about the same test ID appearing multiple times?

**Comment by pmeenan** [comment]
The pipeline picks up HAR files that are named based on the test ID's and the agent will not re-upload a HAR if one with the same name already exists so it shouldn't be possible for the same test ID to show up multiple times.

Worst-case, the agents may test the same page multiple times but all but one of those would be thrown away (and there is protection to try to fast-bail the agent if the HAR already exists in GCS.

**Comment by rviscomi** [comment]
Sounds good. I'll close this issue for now and reopen if we continue seeing this in the next crawl.
