### ISSUE TITLE
Include schemes `ws://` and `wss://` for web sockets in hostname counts

### ISSUE THREAD

**Issue by giancarloaf** [HTTPArchive/data-pipeline#70]
Do we use any other schemes? E.g. `ws://` and `wss://` for web sockets?

_Originally posted by @tunetheweb in https://github.com/HTTPArchive/data-pipeline/pull/34#discussion_r851631118_

**Comment by rviscomi** [comment]
These are logged as errors. Could that possibly be contributing to #72, as if it was handled as a fatal error?
