### ISSUE TITLE
Summary pipeline error: expected int, got float

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#73]
While running 2022_05_12_desktop through the summary pipeline, loading into BigQuery failed with this message:

> Error while reading data, error message: JSON parsing error in row starting at position 5501740: Could not convert value 'number_value: "12.69"' to integer. Field: avg_dom_depth; Value: 12.69

[Dataflow job](https://console.cloud.google.com/dataflow/jobs/us-west1/2022-05-25_22_46_52-12890323822758967482;bottomTab=JOB_LOGS;logsSeverity=ERROR?project=httparchive&pageState=(%22dfTime%22:(%22l%22:%22dfJobMaxTime%22)))

**Comment by tunetheweb** [comment]
Would this explain #72?

**Comment by rviscomi** [comment]
This was a fatal error so I'd expect the mobile table to not be created at all, rather than write too few rows.
 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/1120896/170489294-37230f8f-bb6a-430d-bd5b-b4cf5af8e853.png">

**Comment by tunetheweb** [comment]
But was it fatal for that result only? Or the whole job?

All the ones that wrote back had integer `avg_dom_depth`s

```sql
SELECT
  COUNT(0),
  COUNTIF(ROUND(avg_dom_depth,0) != avg_dom_depth),
FROM
  `httparchive.experimental_summary_pages.2022_05_12_mobile`
```

**Comment by tunetheweb** [comment]
Or did the first 2 million have integer average dom depths and then it stopped?

**Comment by rviscomi** [comment]
The whole job failed, I'm not seeing 2022_05_12_desktop in the summary tables.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/1120896/170490505-71980ad8-1ce5-4b58-9f4c-75d8ce6456e3.png">

**Comment by rviscomi** [comment]
Merged too soon. The pipeline completed successfully but only because the exceptions were being caught. The [logs](https://console.cloud.google.com/logs/query;query=insertId%3D%228264334133763908621:280639:0:37179638%22%20resource.type%3D%22dataflow_step%22%20resource.labels.job_id%3D%222022-05-26_06_20_57-12323347238166322397%22%20%2528logName%3D%22projects%2Fhttparchive%2Flogs%2Fdataflow.googleapis.com%252Fworker%22%20OR%20logName%3D%22projects%2Fhttparchive%2Flogs%2Fdataflow.googleapis.com%252Fworker-startup%22%2529%20timestamp%20%3E%3D%20%222022-05-26T13:20:58.727Z%22%20timestamp%20%3C%3D%20%222022-05-26T16:42:34.404Z%22%20severity%3E%3DWARNING;timeRange=2022-05-26T16:22:33.800Z%2F2022-05-26T16:22:33.800Z;cursorTimestamp=2022-05-26T16:22:33.799260854Z?project=httparchive) show that this field is sometimes `None` and failing to be cast to a float, then int.

**Comment by rviscomi** [comment]
Also @tunetheweb might be right that this is causing #72. I'll rerun the crawl with a fix and see if the row count improves.

**Comment by rviscomi** [comment]
If I'm reading [these logs](https://console.cloud.google.com/logs/query;query=%22import_page%2528%2529%22%0A%22failed%22%0A%22for%22%0A%22status_info%22;timeRange=PT12H;cursorTimestamp=2022-05-26T16:22:33.799260854Z?project=httparchive) correctly, this error should only account for 50k missing pages. 😕

Continuing to look for the rest.

**Comment by tunetheweb** [comment]
Again, are you sure it doesn’t just stop after the first one it encounters?

**Comment by rviscomi** [comment]
I'll know after the next test
