### ISSUE TITLE
Achieve 100% test coverage for all new pipeline code

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#8]
100% is an unrealistic stretch goal, but now that I have your attention... we should improve our test coverage from 0% to something more reasonable.

Identify the most critical areas of the pipeline and those with breakages in the past and add tests to improve our resilience. Ensure that the pipeline can gracefully handle malformed or unexpected inputs.

**Comment by giancarloaf** [comment]
Must have: unit tests

Nice to have: integration tests (e.g. run against a sample of the crawl when it starts)

**Comment by tunetheweb** [comment]
FYI, I'm a big fan of 100% test coverage - even if that involves a lot of `# pragma: no cover` comments so it's not actually 100%. Better to be explicit when it's not covered.

This prevents accidental regressions in coverage levels when new code is added and also encourages tests to be added (`# pragma: no cover` is always there but should not be first choice if it's possible and easy to add a test).
