### ISSUE TITLE
Renew HTTP Archive API Key

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#95]
I had a reminder on my calendar for "Renew HTTP Archive API Key" on Monday. The note from @tunetheweb in the event says:

> The API key used to import the runs into BigQuery expiries every 3 months, leading to an "Invalid JWT Signature." import error and no tables created for that month.
> 
> To renew, a few days in advance fo expiration date ideally!
> 
> - Go to: [https://console.cloud.google.com/apis/credentials?project=httparchive](https://www.google.com/url?q=https://console.cloud.google.com/apis/credentials?project%3Dhttparchive&sa=D&source=calendar&ust=1656305909939828&usg=AOvVaw0FEVvO5c7YBqJQdaVLVnjB)
> - Select [dataflow-service-account@httparchive.iam.gserviceaccount.com](https://www.google.com/url?q=https://console.cloud.google.com/iam-admin/serviceaccounts/details/115218110380863142314;edit%3Dtrue?previousPage%3D%252Fapis%252Fcredentials%253Fauthuser%253D1%2526project%253Dhttparchive%26authuser%3D1%26project%3Dhttparchive&sa=D&source=calendar&ust=1656305909939828&usg=AOvVaw346oRZabKLeHSPopapMHMf)
> - Select Keys tab
> - Note the soon to be expiring key
> - Add a new key (in JSON format)
> - Download it
> - Go to [https://console.cloud.google.com/compute/instances?project=httparchive](https://www.google.com/url?q=https://console.cloud.google.com/compute/instances?project%3Dhttparchive&sa=D&source=calendar&ust=1656305909939828&usg=AOvVaw2tlqyykC6dU9GjL75eihFU)
> - Order by name (descending) until Worker machine shows up
> - SSH onto Worker machine
> - sudo su -
> - Edit /home/igrigorik/code/dataflow/python/credentials/auth.json and replace the entire JSON key with the new one
> - Either rerun the job as igrigorik from the code directory (nohup ./sync_har.sh chrome >> /var/log/HA-import-har-chrome.log 2>&1 &) or wait for the automatic kick off next day.
> 
> Then copy this info into a new calendar invite for us all for next expiration time so we won't forget.
> 
> Must find a better way to handle this, but this'll do for now...

This might become obsolete soon after #38 in which we'll be merging the non-summary and summary pipelines to be streaming. Until then, maybe we should renew the API key one last time to avoid hiccups next month.

**Comment by tunetheweb** [comment]
Ah yes meant to do this.

Done now.

Will stick another calendar reminder in just in case but, as you say, hopefully not required next time.
